### ISSUE TITLE
recognition of Code Blocks

### ISSUE THREAD

**Issue by solariz** [vyleung/logseq-copy-code-plugin#1]
Hey,

as written on Twitter, thanks alot for that absolutely useful plugin. 
I directly downloaded and tried it, there seems on my graph a bit strange behavior. Sometimes the Plugin only display the code copy icon after a manual refresh. If I open a block and go back the Icons are gone again. Also some Code blocks are not found at all.

I captured a small screen rec to better show it:
https://www.loom.com/share/86a8568970974d4abf7385b241488f9b

**Comment by vyleung** [comment]
hi Marco, glad you find the plugin useful! thanks for the screen recording
> If I open a block and go back the Icons are gone again.
- this is a known issue - please see the README [here](https://github.com/vyleung/logseq-copy-code-plugin#copy-code-from-code-blocks) for workarounds. this happens because the copy code icon is a child of the code block editor, so if you enter edit mode, the code block editor disappears and so does the icon

> some Code blocks are not found at all.
- i noticed in your screen recording that you had 2 code blocks in a block - the plugin doesn't currently support having multiple code blocks in one block

i'll work on figuring out solutions to these issues 🙂

**Comment by solariz** [comment]
Thanks,

if it is just 1 per Block it's fine. I can just tidy up my mess and write a new block per code :) 

For the dissapearing copy button, understood; Would be great if there maybe a way to auto hook some kind of event to regullary refresh the icon if it is missing again.

Cheers.

**Comment by vyleung** [comment]
both issues should be addressed in [v.1.0.1](https://github.com/vyleung/logseq-copy-code-plugin/releases/tag/v.1.0.1) - please let me know if they have been fixed

**Comment by solariz** [comment]
Hey,

sorry for the late response. Unfortunately now it doesn't recognize any code block at all. Even reloading the plugin or block doesent do the trick.

Here is a code block I use for testing:
https://tools.3q.de/paste/?197bb69b1202ef3b#4ozshhrtaLnWXRQ5hJRJ2AG5h4pWpKvt81xdEcmyKUbC

I have more time next week and will have a look if I can find out if maybe an other plugin is interfering here.

Thank you.

**Comment by vyleung** [comment]
i found that installing the plugin via the marketplace displays a cross-origin error. i've attempted to address the error in this [pull request](https://github.com/logseq/marketplace/pull/177)

**Comment by vyleung** [comment]
please try re-installing the plugin via the marketplace - it should work normally now

**Comment by solariz** [comment]
Works great now. thanks !

**Comment by vyleung** [comment]
happy to hear that!
